// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type ChatRequest = { messages: Array<ChatMessage>, model: string, temperature: number, systemPrompt: string | null, };
